# --- Source global definitions --- #

if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# --- Additional Config ----------- #

source ~/.dotfiles/bash/aliases
source ~/.dotfiles/bash/functions

# --- Colors ---------------------- #

export CLICOLOR=1
export TERM=xterm-color

# --- Editor ---------------------- #

export EDITOR=nano

# --- Paths ----------------------- #

PATH=${PATH}:/usr/local/bin:~/.composer/vendor/bin
